# Stage 1: Build React App
FROM node:latest as build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Stage 2: Serve React App with Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]